name: Chain Config Validation

on:
  pull_request:
    branches: [ main ] # Or your default branch
    paths:
      - 'chains/**.json' # Only run if JSON files in chains/ change

jobs:
  validate-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for changed-files

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your preferred Node.js version
          cache: 'npm' # Enable caching for npm, uses package-lock.json
          cache-dependency-path: scripts/config-validator/package-lock.json # Specify lock file path

      - name: Get changed JSON files in chains/
        id: changed-files
        uses: tj-actions/changed-files@v41 # Use a specific version
        with:
          files: chains/**/*.json

      - name: Install JSON Schema Validator (ajv-cli)
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm install -g ajv-cli@latest # Explicitly install latest version

      - name: Install Validator Script Dependencies
        if: steps.changed-files.outputs.any_changed == 'true' # Only install if JSONs changed
        working-directory: ./scripts/config-validator
        run: npm install

      # Add build step if necessary, e.g., npm run build
      # - name: Build Validator Script
      #   if: steps.changed-files.outputs.any_changed == 'true'
      #   working-directory: ./scripts/config-validator
      #   run: npm run build # Assuming you have a build script in package.json

      - name: Validate Changed Files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed JSON files in chains/: ${{ steps.changed-files.outputs.all_changed_files }}"
          VALIDATION_FAILED=false
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Processing $file..."
            FILE_VALIDATION_PASSED=false

            # Check if the file structure looks like a chain config
            if [[ "$file" == chains/*/*.json ]]; then # Basic check for chains/ANYTHING/some.json

              # Step 1: Attempt Initia validation script (which now includes schema check)
              echo "Attempting Initia validation script (incl. schema) for $file..."
              if npx ts-node $GITHUB_WORKSPACE/scripts/config-validator/src/validate-initia.ts "$GITHUB_WORKSPACE/$file"; then
                echo "---> Validation PASSED for Initia chain $file (Script Succeeded)."
                FILE_VALIDATION_PASSED=true
              else
                echo "Initia script failed or did not identify $file as an Initia chain."
                echo "Attempting fallback: Validating $file against general schema using validate-general.ts..."
                # Step 2: If Initia script fails, try general schema validation as fallback using custom script
                if npx ts-node $GITHUB_WORKSPACE/scripts/config-validator/src/validate-general.ts "$GITHUB_WORKSPACE/$file"; then
                  echo "---> Validation PASSED for non-Initia chain $file (General Schema OK)."
                  FILE_VALIDATION_PASSED=true
                else
                  echo "---> Validation FAILED for non-Initia chain $file (General Schema Failed)."
                  # FILE_VALIDATION_PASSED remains false
                fi
              fi
            else
              echo "Skipping file (does not match chains/*/*.json pattern): $file"
              # Consider if skipped files should cause failure? Currently they don't.
            fi

            if [[ "$FILE_VALIDATION_PASSED" == false && "$file" == chains/*/*.json ]]; then
                # Only set global failure if a chain file actually failed validation
                VALIDATION_FAILED=true
            fi

            echo # Add a newline for readability between files
          done

          # Final check
          if [[ "$VALIDATION_FAILED" == true ]]; then
            echo "One or more configuration validations failed."
            exit 1
          else
            echo "All configuration validations passed."
          fi 